import { existsSync, writeFileSync, chmodSync } from "fs";
import { join } from "path";
import { promptConfirm } from "../utils/prompt.js";
import { getRalphDir } from "../utils/config.js";

const RALPH_ONCE_SH = `#!/usr/bin/env bash
# Generated by ralph-cli
# Run a single automation iteration

set -e

SCRIPT_DIR="$(cd "$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
RALPH_DIR="$SCRIPT_DIR/.ralph"

if [ ! -f "$RALPH_DIR/prompt.md" ]; then
  echo "Error: .ralph/prompt.md not found. Run 'ralph init' first."
  exit 1
fi

PROMPT=$(cat "$RALPH_DIR/prompt.md")

claude --permission-mode acceptEdits --dangerously-skip-permissions \\
  -p "@$RALPH_DIR/prd.json @$RALPH_DIR/progress.txt $PROMPT"
`;

const RALPH_SH = `#!/usr/bin/env bash
# Generated by ralph-cli
# Run multiple automation iterations

set -e

SCRIPT_DIR="$(cd "$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
RALPH_DIR="$SCRIPT_DIR/.ralph"

if [ -z "$1" ]; then
  echo "Usage: ./ralph.sh <iterations>"
  echo "  <iterations>  Number of automation cycles to run"
  exit 1
fi

if ! [[ "$1" =~ ^[0-9]+$ ]] || [ "$1" -lt 1 ]; then
  echo "Error: iterations must be a positive integer"
  exit 1
fi

ITERATIONS=$1

if [ ! -f "$RALPH_DIR/prompt.md" ]; then
  echo "Error: .ralph/prompt.md not found. Run 'ralph init' first."
  exit 1
fi

PROMPT=$(cat "$RALPH_DIR/prompt.md")

TEMP_FILE=$(mktemp)
trap "rm -f $TEMP_FILE" EXIT

for ((i=1; i<=ITERATIONS; i++)); do
  echo ""
  echo "=================================================="
  echo "Iteration $i of $ITERATIONS"
  echo "=================================================="
  echo ""

  set +e
  claude --permission-mode acceptEdits --dangerously-skip-permissions \\
    -p "@$RALPH_DIR/prd.json @$RALPH_DIR/progress.txt $PROMPT" | tee "$TEMP_FILE"
  set -e

  if grep -q "<promise>COMPLETE</promise>" "$TEMP_FILE"; then
    echo ""
    echo "=================================================="
    echo "PRD COMPLETE - All features implemented!"
    echo "=================================================="

    # Try to send notification (optional)
    if command -v tt &> /dev/null; then
      tt notify "Ralph: PRD Complete!"
    fi

    break
  fi
done

echo ""
echo "Ralph run finished."
`;

export async function scripts(_args: string[]): Promise<void> {
  const cwd = process.cwd();
  const ralphDir = getRalphDir();

  // Check if .ralph directory exists (means init was run)
  if (!existsSync(ralphDir)) {
    console.error("Error: .ralph/ directory not found. Run 'ralph init' first.");
    process.exit(1);
  }

  console.log("Generate shell scripts for sandboxed environments\n");

  const files = [
    { name: "ralph.sh", content: RALPH_SH },
    { name: "ralph-once.sh", content: RALPH_ONCE_SH },
  ];

  for (const file of files) {
    const filePath = join(cwd, file.name);

    if (existsSync(filePath)) {
      const overwrite = await promptConfirm(`${file.name} already exists. Overwrite?`);
      if (!overwrite) {
        console.log(`Skipped ${file.name}`);
        continue;
      }
    }

    writeFileSync(filePath, file.content);
    chmodSync(filePath, 0o755);
    console.log(`Created ${file.name}`);
  }

  console.log("\nShell scripts created! Usage:");
  console.log("  ./ralph-once.sh      # Single iteration");
  console.log("  ./ralph.sh 5         # Run 5 iterations");
}
